version: '3'

services:
  nginx:
    container_name: nginx
    build:          ./requirements/nginx
    ports:
                    - "443:443"
    restart:        always
    volumes:
                    - wp_file:/var/www/html
    networks:
                    - inception